### ISSUE TITLE
Ask for help adout call win32 api in flex to set window display affinity

### ISSUE THREAD

**Issue by xuqisheng** [somanuell/SoBrowserAction#1]
hello manuell,
i find your answer to make adobe air desktop application  gives "all black" Client Area when do print screen.
Can you send me the example code ?

Thank you very much for your help !~~
 
Email: xuqisheng3344@gmail.com
Link: https://stackoverflow.com/questions/30723579/call-win32-api-in-flex-to-set-window-display-affinity?rq=1

**Comment by somanuell** [comment]
Hi Andy,
I am very sorry, but the code you talk about is more than 6 years old and I have no idea where it is.
I changed PC two times since then...
You should comment on my answser on SO. I may be abble to help.
